### ISSUE TITLE
train_src.py 내 train_step 함수에 대한 질문입니다.

### ISSUE THREAD

**Issue by shlee625** [JWoong148/MetaPerturb#1]
안녕하세요. 우선 코드를 공유해주셔서 감사합니다. 건강에 유의하시길 바라겠습니다.

제가 이해한 바가 맞다면, meta-training 단계에서는 기존 방식처럼 initialization weights &theta;를 학습하는 게 아니라
perturbation function의 parameter &phi;를 학습하는 것으로 알고 있습니다. 이때 논문의 Algorithm 1 12번줄에 따르면
inner loop의 각 step 별로 계산한 loss들(10번줄)을 다 따로 저장해뒀다가 inner loop가 끝나고 난 뒤에 mean 값을 구해서
이를 이용하여 &phi;를 update한다고 나와 있습니다.
하지만 `train_src.py` 파일 내 `train_step` 함수를 보면 &theta;와 &phi;가 한 스텝 내에서 같이 update되는 것으로 보입니다.
이렇게 되면 inner loop의 매 step마다 Algorithm 1에서는 같은 &phi;를 통해 perturbation을 수행할 것이고 실제 코드에서는
step마다 update된 &phi;가 perturbation을 수행하게 될텐데 어떠한 것이 맞는 것인지 여쭙고 싶습니다.

**Comment by JWoong148** [comment]
안녕하세요, 저희 연구에 관심을 가져주셔서 감사합니다. 

먼저, `train_src.py` 는 multiprocessing을 통한 Parallel learning을 염두에 두고 작성한 코드입니다. Sequential하게 학습하는 경우, 지적하신 바와 같이 loss를 저장해두고 inner loop 이후 update하는 것이 맞습니다. Parallel하게 학습하는 경우, loss를 프로세스마다 (task마다) 계산하고 108번 줄  `share_grads(phi)` 를 통해 프로세스간 phi의 그래디언트를 share하여 mean을 취하는 방식입니다. (phi를 모두 share하는 것보다 gradient만 share하여 업데이트하는 것이 계산상 효율적입니다.) 이렇게 계산하면 프로세스마다 같은 phi를 사용하고 업데이트는 전체 프로세스의 결과를 사용하며 업데이트 이후에도 phi는 프로세스마다 같은 값으로 유지됩니다.

감사합니다.

**Comment by shlee625** [comment]
> 안녕하세요, 저희 연구에 관심을 가져주셔서 감사합니다.
> 
> 먼저, `train_src.py` 는 multiprocessing을 통한 Parallel learning을 염두에 두고 작성한 코드입니다. Sequential하게 학습하는 경우, 지적하신 바와 같이 loss를 저장해두고 inner loop 이후 update하는 것이 맞습니다. Parallel하게 학습하는 경우, loss를 프로세스마다 (task마다) 계산하고 108번 줄 `share_grads(phi)` 를 통해 프로세스간 phi의 그래디언트를 share하여 mean을 취하는 방식입니다. (phi를 모두 share하는 것보다 gradient만 share하여 업데이트하는 것이 계산상 효율적입니다.) 이렇게 계산하면 프로세스마다 같은 phi를 사용하고 업데이트는 전체 프로세스의 결과를 사용하며 업데이트 이후에도 phi는 프로세스마다 같은 값으로 유지됩니다.
> 
> 감사합니다.

이해가 됐습니다. 감사합니다.
